version: "3.8"
services:

    # MySQL Service
    db:
        image: mysql:5.7
        container_name: "MySQL"
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=mountain_routes
            - MYSQL_ROOT_PASSWORD=root
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        

    # PHP Service
    php:
        build:
            context: ./BackEnd
            target: php
        container_name: "Backend"
        environment:
            - CONTAINER_ROLE=app
        # working_dir: /var/www/html
        command: bash -c "service apache2 start; cd /home/proyecto/BackEnd; sleep 100; exec Docker/entrypoint.sh;"
        restart: always
        ports:
            -   80:80
        depends_on:
            - db


volumes:
    db-data: ~